        <style type="text/css">

                    .highcharts-data-table table {
                        font-family: Verdana, sans-serif;
                        border-collapse: collapse;
                        border: 1px solid #EBEBEB;
                        margin: 10px auto;
                        text-align: center;
                        width: 100%;
                        max-width: 500px;
                    }

                    .highcharts-data-table th {
                        font-weight: 600;
                        padding: 0.5em;
                    }
                    .highcharts-data-table td, .highcharts-data-table th, .highcharts-data-table caption {
                        padding: 0.5em;
                    }
                    .highcharts-data-table thead tr, .highcharts-data-table tr:nth-child(even) {
                        background: #f8f8f8;
                    }
                    .highcharts-data-table tr:hover {
                        background: #f1f7ff;
                }
        /* /////////////////// cho pie 3d */
                #container {
                height: 400px; 
                }

                .highcharts-figure, .highcharts-data-table table {
                min-width: 310px; 
                max-width: 800px;
                margin: 1em auto;
                }

                .highcharts-data-table table {
                font-family: Verdana, sans-serif;
                border-collapse: collapse;
                border: 1px solid #EBEBEB;
                margin: 10px auto;
                text-align: center;
                width: 100%;
                max-width: 500px;
                }
                .highcharts-data-table caption {
                padding: 1em 0;
                font-size: 1.2em;
                color: #555;
                }
                .highcharts-data-table th {
                font-weight: 600;
                padding: 0.5em;
                }
                .highcharts-data-table td, .highcharts-data-table th, .highcharts-data-table caption {
                padding: 0.5em;
                }
                .highcharts-data-table thead tr, .highcharts-data-table tr:nth-child(even) {
                background: #f8f8f8;
                }
                .highcharts-data-table tr:hover {
                background: #f1f7ff;
                }
        /* /////////////////// */
		</style>

    <div>
        <div style="width: 50%; float: left;">
            <figure class="highcharts-figure">
                <div id="aaaa"></div>
                <p class="highcharts-description">
                    Basic line chart showing trends in a dataset. This chart includes the
                    <code>series-label</code> module, which adds a label to each line for
                    enhanced readability.
                </p>
            </figure>
        </div>
        <div style="width: 50%; float: left;">
            <figure class="highcharts-figure">
                <div id="containerxxx"></div>
                <p class="highcharts-description">
                    Basic line chart showing trends in a dataset. This chart includes the
                    <code>series-label</code> module, which adds a label to each line for
                    enhanced readability.
                </p>
            </figure>
        </div>
    </div>

    <div>
        <div style="width: 50%; float: left;">
            <figure class="highcharts-figure">
                <div id="containeryyy"></div>
                    <p class="highcharts-description">
                        Basic line chart showing trends in a dataset. This chart includes the
                        <code>series-label</code> module, which adds a label to each line for
                        enhanced readability.
                    </p>
            </figure>
        </div>
        <div style="width: 50%; float: left;">
            <figure class="highcharts-figure">
                <div id="container"></div>
                <p class="highcharts-description">
                    Chart demonstrating the use of a 3D pie layout.
                    The "Chrome" slice has been selected, and is offset from the pie.
                    Click on slices to select and unselect them.
                    Note that 3D pies, while decorative, can be hard to read, and the
                    viewing angles can make slices close to the user appear larger than they
                    are.
                </p>
            </figure>
        </div>
    </div>

<script type="text/javascript">
    var da = <?php echo $block->order_by_status(); ?>;
    var week = <?php echo json_encode($block->arr_don()['time']); ?>;
    require(['jquery', 'highcharts'], function ($, Highcharts) {
        $(document).ready(function ($) {
            // ******************************* Extras ***************************************************

            Highcharts.wrap(Highcharts.Axis.prototype, 'getLinePath', function (proceed, lineWidth) {
                var axis = this,
                    path = proceed.call(this, lineWidth),
                    x = path[1],
                    y = path[2];

                Highcharts.each(this.breakArray || [], function (brk) {
                    if (axis.horiz) {
                        x = axis.toPixels(brk.from);
                        path.splice(3, 0,
                            'L', x - 4, y, // stop
                            'M', x - 9, y + 5, 'L', x + 1, y - 5, // left slanted line
                            'M', x - 1, y + 5, 'L', x + 9, y - 5, // higher slanted line
                            'M', x + 4, y
                        );
                    } else {
                        y = axis.toPixels(brk.from);
                        path.splice(3, 0,
                            'L', x, y - 4, // stop
                            'M', x + 5, y - 9, 'L', x - 5, y + 1, // lower slanted line
                            'M', x + 5, y - 1, 'L', x - 5, y + 9, // higher slanted line
                            'M', x, y + 4
                        );
                    }
                });
                return path;
            });

            var pointBreakColumn = function (e) {
                var point = e.point,
                    brk = e.brk,
                    shapeArgs = point.shapeArgs,
                    x = shapeArgs.x,
                    y = this.translate(brk.from, 0, 1, 0, 1),
                    w = shapeArgs.width,
                    key = ['brk', brk.from, brk.to],
                    path = ['M', x, y, 'L', x + w * 0.25, y + 4, 'L', x + w * 0.75, y - 4, 'L', x + w, y];

                if (!point[key]) {
                    point[key] = this.chart.renderer.path(path)
                        .attr({
                            'stroke-width': 2,
                            stroke: point.series.options.borderColor
                        })
                        .add(point.graphic.parentGroup);
                } else {
                    point[key].attr({
                        d: path
                    });
                }
            };


// *****************************************************************
            Highcharts.chart('containeryyy', {
                chart: {
                    type: 'column'
                },
                title: {
                    text: 'Visualized axis break'
                },
                xAxis: {
                    categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
                },
                yAxis: {
                    lineColor: 'black',
                    lineWidth: 2,
                    title: false,
                    tickInterval: 100,
                    breaks: [{
                        from: 500,
                        to: 3000
                    }],
                    events: {
                        pointBreak: pointBreakColumn
                    }
                },
                series: [{
                    name: 'Attraction 1',
                    data: [44, 128, 180, 345, 3050, 3590, 3840, 3630, 3120, 420, 240, 80]
                }, {
                    name: 'Attraction 2',
                    data: [64, 138, 164, 408, 3120, 3540, 3875, 3420, 720, 320, 160, 20]
                }]

            });

            Highcharts.chart('containerxxx', {
                chart: {
                    type: 'column'
                },
                title: {
                    text: 'World\'s largest cities per 2017'
                },
                subtitle: {
                    text: 'Source: <a href="http://en.wikipedia.org/wiki/List_of_cities_proper_by_population">Wikipedia</a>'
                },
                xAxis: {
                    type: 'category',
                    labels: {
                        rotation: -45,
                        style: {
                            fontSize: '13px',
                            fontFamily: 'Verdana, sans-serif'
                        }
                    }
                },
                yAxis: {
                    min: 0,
                    title: {
                        text: 'Population (millions)'
                    }
                },
                legend: {
                    enabled: false
                },
                tooltip: {
                    pointFormat: 'Population in 2017: <b>{point.y:.1f} millions</b>'
                },
                series: [{
                    name: 'Population',
                    data: da,
                    dataLabels: {
                        enabled: true,
                        rotation: -90,
                        color: '#FFFFFF',
                        align: 'right',
                        format: '{point.y:.1f}', // one decimal
                        y: 10, // 10 pixels down from the top
                        style: {
                            fontSize: '13px',
                            fontFamily: 'Verdana, sans-serif'
                        }
                    }
                }]
            });

            Highcharts.chart('container', {
                chart: {
                    type: 'pie',
                    options3d: {
                        enabled: true,
                        alpha: 45,
                        beta: 0
                    }
                },
                title: {
                    text: 'đơn hàng theo trạng thái'
                },
                accessibility: {
                    point: {
                        valueSuffix: '%'
                    }
                },
                tooltip: {
                    pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
                },
                plotOptions: {
                    pie: {
                        allowPointSelect: true,
                        cursor: 'pointer',
                        depth: 35,
                        dataLabels: {
                            enabled: true,
                            format: '{point.name}'
                        }
                    }
                },
                series: [{
                    type: 'pie',
                    name: 'Browser share',
                    data: da
                    //  [
                    //     ['Firefox', 45.0],
                    //     ['IE', 26.8],
                    //     ['chorme', 30],
                    //     ['Safari', 8.5],
                    //     ['Opera', 6.2],
                    //     ['Others', 12]
                    // ]
                }]
            });

            Highcharts.chart('aaaa', {

                title: {
                    text: 'tổng hợp đơn hàng trong tuần'
                },

                subtitle: {
                    text: 'Source: zxc.com/magento2'
                },

                yAxis: {
                    title: {
                        text: 'số đơn'
                    }
                },

                xAxis: {
                    accessibility: {
                        rangeDescription: 'ngày trong tuần'
                    },
                    categories: week

                },

                legend: {
                    layout: 'vertical',
                    align: 'right',
                    verticalAlign: 'middle'
                },

                series: [{
                    name: 'order',
                    data: [12, 23, 34, 21, 32, 65, 3]
                }],

                responsive: {
                    rules: [{
                        condition: {
                            maxWidth: 500
                        },
                        chartOptions: {
                            legend: {
                                layout: 'horizontal',
                                align: 'center',
                                verticalAlign: 'bottom'
                            }
                        }
                    }]
                }

                });
        

            // Highcharts.chart('aaaa', {
            //     title: { text: 'đơn hàng trong tuần' },
            //     xAxis: { categories: ['as', 'aa', 'p', 'opop', 'jk'] },
            //     yAxis: {
            //         title: { text: '(số đơn)' },
            //         plotLines: [{ value: 0, width: 1, color: '#FFFFFF' }]
            //     },
            //     tooltip: { valueSuffix: 'đơn' },
            //     legend: {
            //         layout: 'vertical',
            //         align: 'right',
            //         verticalAlign: 'middle',
            //         borderWidth: 0
            //     },
            //     series: [da]
            // });
    });
 });
</script>