<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Tha\Nan\Block\Onepage */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>

<div id="checkout" data-bind="scope:'checkout'" class="checkout-container">
    <div id="checkout-loader" data-role="checkout-loader" class="loading-mask" data-mage-init='{"checkoutLoader": {}}'>
        <div class="loader">
            <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/loader-1.gif')) ?>"
                 alt="<?= $block->escapeHtmlAttr(__('Loading...')) ?>">
        </div>
    </div>
    <?= /* @noEscape */ $secureRenderer->renderStyleAsTag("position: absolute;", "#checkout-loader img") ?>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <?php $JsLayout = $block->getJsLayout(); ?>
    <script type="text/x-magento-init">
        {
            "#checkout": {
                "Magento_Ui/js/core/app": <?= /* @noEscape */ $JsLayout  ?>
            }
        }
    </script>

    <script>
        require([
            'mage/url',
            'Magento_Ui/js/block-loader',
            'Magento_Checkout/js/model/payment-service',
            'Magento_Checkout/js/model/payment/method-converter',
            'Magento_Checkout/js/action/set-shipping-information',
            'Magento_Checkout/js/model/quote',
            'Magento_Checkout/js/model/address-converter',
            'Magento_Checkout/js/checkout-data'
        ], function(url, blockLoader, paymentService, methodConverter, setShippingInformationAction, quote, addressConverter, checkoutData) {

            quote.shippingMethod(<?php echo($block->selected_shipping_method() != 'null' ? $block->selected_shipping_method() : json_encode(["method_code" => "tha_nan", "carrier_code" => "tha nan"])); ?>);

            quote.shippingAddress(addressConverter.addressToEstimationAddress(window.checkoutConfig.shippingAddressFromData));
            
            setShippingInformationAction();
            // checkoutData.subscribe(function (data) {
            //     // self.createRendererComponent(address);
            //     console.log(data);
            // })
        });
    </script>

    <?php $serializedCheckoutConfig = /* @noEscape */ $block->getSerializedCheckoutConfig();
    $scriptString = <<<script
        window.checkoutConfig = {$serializedCheckoutConfig};
        window.JsLayout = {$JsLayout};
        // Create aliases for customer.js model from customer module
        window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
        window.customerData = window.checkoutConfig.customerData;
script;
    ?>
    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
    <?php $scriptString = <<<script
        require([
            'mage/url',
            'Magento_Ui/js/block-loader'
        ], function(url, blockLoader) {
            blockLoader("{$block->escapeJs($block->escapeUrl($block->getViewFileUrl('images/loader-1.gif')))}");
            return url.setBaseUrl('{$block->escapeJs($block->escapeUrl($block->getBaseUrl()))}');
        })
script;
    ?>
    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
</div>
