<p style="color: rebeccapurple;">js companent</p>

<div data-bind="scope: 'tha_mycomponent'">
    <div data-bind="text: title"></div>
</div>
<script type="text/x-magento-init">
    {
        "*":{
            "Magento_Ui/js/core/app": {
                "components":{
                    "tha_mycomponent":{
                        "component": "Tha_Nan/js/tha_component",
                        "modulename ": "<?= $block->escapeJs($block->getModuleName()); ?>",
                        "key_1": "key1 value",
                        "tha_key": "tha_key value",
                        "name": "name data"
                    }
                }
            }
        }
    }
</script>